### ISSUE TITLE
HTTP 500 when no entries exist

### ISSUE THREAD

**Issue by adamralph** [Particular/HashBus#133]

**Comment by sfarmar** [comment]
Adam's response in slack:
it's because of this https://github.com/Particular/HashBus/blob/4824a18d3e567d870331aa5bc263ef6c5595e4bc/src/HashBus.WebApi/MostMentionedModule.cs#L43
(and also the previous line)
when the list is empty, the Min and Max throw exceptions
it's the same in all 6 modules
the property on the contracts is already nullable so I guess it's just a case of changing it to something like `list.Any() ? list.Min(..) : null` (edited)
it's also worth checking whether the viewers can handle nulls for those values
